# Generated by Django 4.1.7 on 2023-04-22 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('Checking', 'Checking'), ('Savings', 'Savings'), ('Credit Card', 'Credit Card'), ('Cash', 'Cash'), ('Investment', 'Investment'), ('M-Pesa', 'M-Pesa')], max_length=255)),
                ('deposited_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposited_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='BudgetCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('budget_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('cheque_number', models.CharField(blank=True, max_length=255)),
                ('amount_spent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.account')),
                ('budget_categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.budgetcategorie')),
            ],
        ),
    ]
