# Generated by Django 4.1.7 on 2023-03-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(choices=[('Account Options', (('M-Pesa', 'M-Pesa'), ('Bank', 'Bank'), ('Credit_Card', 'Credit_Card')))], max_length=50)),
                ('saving_list', models.CharField(choices=[('Account Options', (('salary', 'salary'), ('saving', 'saving'), ('investment', 'investment')))], max_length=50)),
                ('deposited_amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('deposited_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='BudgetCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Utilities, groceries, etc.', max_length=100)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=19)),
                ('date_budgeted', models.DateField()),
            ],
        ),
    ]
