# Generated by Django 4.1.7 on 2023-03-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='deposited_amount',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='budgetcategorie',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
