# Generated by Django 4.1.7 on 2023-03-31 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_account_deposited_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.CharField(help_text='store name', max_length=200)),
                ('trasaction_date', models.DateField()),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.account')),
                ('budget_categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.budgetcategorie')),
            ],
        ),
    ]
