# Generated by Django 4.1.7 on 2023-03-31 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
    ]
