# Generated by Django 4.1.7 on 2023-04-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_budgetcategorie_budget_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='deposited_amount',
        ),
        migrations.RemoveField(
            model_name='account',
            name='saving_list',
        ),
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('Checking', 'Checking'), ('Savings', 'Savings'), ('Credit Card', 'Credit Card'), ('Cash', 'Cash'), ('Investment', 'Investment'), ('M-Pesa', 'M-Pesa')], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='starting_balance',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
